package model.theme;

/**
 * All theme values that can be registered and bind to a Color.
 * @author TRAFNY Theo - UPSSITECH
 *
 */
public enum ThemeValue {

	BACKGROUND,
	BACKGROUND_JOYSTICK,
	JOYSTICK,
	BACKGROUND_ROBOT_MAP,
	
	TOGGLE_BUTTONS_ON,
	TOGGLE_BUTTONS_OFF,
	BLUETOOTH_INDICATOR_ON,
	TOGGLE_BUTTONS_MASK,
	
	AUTONOMOUS_SWITCH,
	AUTONOMOUS_SWITCH_ON,
	AUTONOMOUS_SWITCH_OFF,
	
	BACKGROUND_BUTTONS,
	
	TEXT,
	
	BACKGROUND_BATTERY,
	BATTERY_FULL,
	BATTERY_LOW,
	BATTERY_EMPTY,
	
	ROBOT_COLOR,
	TITLE_BAR;
	
}